# Generated by Django 6.0.6 on 2026-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, max_length=5, verbose_name='Bewertung'),
        ),
        migrations.AlterField(
            model_name='monthlyoffer',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Angebot aktiv?'),
        ),
        migrations.AlterField(
            model_name='monthlyoffer',
            name='image',
            field=models.ImageField(upload_to='offers', verbose_name='Angebotsbild'),
        ),
    ]
